from dataclasses import dataclass

@dataclass(frozen=True)
class ActionsEnum:
    BALANCE_HISTORY: str = "balancehistory"
    BALANCE_MULTI: str = "balancemulti"
    BALANCE: str = "balance"
    CHAIN_SIZE: str = "chainsize"
    DAILY_AVG_BLOCK_SIZE: str = "dailyavgblocksize"
    DAILY_AVG_BLOCK_TIME: str = "dailyavgblocktime"
    DAILY_AVG_GAS_LIMIT: str = "dailyavggaslimit"
    DAILY_AVG_GAS_PRICE: str = "dailyavggasprice"
    DAILY_AVG_HASH_RATE: str = "dailyavghashrate"
    DAILY_AVG_NET_DIFFICULTY: str = "dailyavgnetdifficulty"
    DAILY_BLK_COUNT: str = "dailyblkcount"
    DAILY_BLOCK_REWARDS: str = "dailyblockrewards"
    DAILY_GAS_USED: str = "dailygasused"
    DAILY_NET_UTILIZATION: str = "dailynetutilization"
    DAILY_NEW_ADDRESS: str = "dailynewaddress"
    DAILY_TX: str = "dailytx"
    DAILY_TXN_FEE: str = "dailytxnfee"
    DAILY_UNCLE_BLK_COUNT: str = "dailyuncleblkcount"
    ETH_BLOCK_NUMBER: str = "eth_blockNumber"
    ETH_CALL: str = "eth_call"
    ETH_DAILY_MARKET_CAP: str = "ethdailymarketcap"
    ETH_DAILY_PRICE: str = "ethdailyprice"
    ETH_ESTIMATE_GAS: str = "eth_estimateGas"
    ETH_GAS_PRICE: str = "eth_gasPrice"
    ETH_GET_BLOCK_BY_NUMBER: str = "eth_getBlockByNumber"
    ETH_GET_BLOCK_TRANSACTION_COUNT_BY_NUMBER: str = (
        "eth_getBlockTransactionCountByNumber"
    )
    ETH_GET_CODE: str = "eth_getCode"
    ETH_GET_STORAGE_AT: str = "eth_getStorageAt"
    ETH_GET_TRANSACTION_BY_BLOCK_NUMBER_AND_INDEX: str = (
        "eth_getTransactionByBlockNumberAndIndex"
    )
    ETH_GET_TRANSACTION_BY_HASH: str = "eth_getTransactionByHash"
    ETH_GET_TRANSACTION_COUNT: str = "eth_getTransactionCount"
    ETH_GET_TRANSACTION_RECEIPT: str = "eth_getTransactionReceipt"
    ETH_GET_UNCLE_BY_BLOCK_NUMBER_AND_INDEX: str = "eth_getUncleByBlockNumberAndIndex"
    ETH_PRICE: str = "ethprice"
    ETH_SUPPLY: str = "ethsupply"
    GAS_ESTIMATE: str = "gasestimate"
    GAS_ORACLE: str = "gasoracle"
    GET_ABI: str = "getabi"
    GET_BLOCK_COUNTDOWN: str = "getblockcountdown"
    GET_BLOCK_NUMBER_BY_TIME: str = "getblocknobytime"
    GET_BLOCK_REWARD: str = "getblockreward"
    GET_MINED_BLOCKS: str = "getminedblocks"
    GET_SOURCE_CODE: str = "getsourcecode"
    GET_STATUS: str = "getstatus"
    GET_TX_RECEIPT_STATUS: str = "gettxreceiptstatus"
    TOKEN_BALANCE_HISTORY: str = "tokenbalancehistory"
    TOKEN_BALANCE: str = "tokenbalance"
    TOKEN_INFO: str = "tokeninfo"
    TOKEN_SUPPLY_HISTORY: str = "tokensupplyhistory"
    TOKEN_SUPPLY: str = "tokensupply"
    TOKENNFTTX: str = "tokennfttx"
    TOKENTX: str = "tokentx"
    TXLIST_INTERNAL: str = "txlistinternal"
    TXLIST: str = "txlist"

@dataclass(frozen=True)
class ModulesEnum:
    ACCOUNT: str = "account"
    BLOCK: str = "block"
    CONTRACT: str = "contract"
    GASTRACKER: str = "gastracker"
    PROXY: str = "proxy"
    STATS: str = "stats"
    TOKEN: str = "token"
    TRANSACTION: str = "transaction"

@dataclass(frozen=True)
class FieldsEnum:
    ACTION: str = "&action="
    ADDRESS: str = "&address="
    API_KEY: str = "&apikey="
    BLOCK_TYPE: str = "&blocktype="
    BLOCKNO: str = "&blockno="
    BOOLEAN: str = "&boolean="
    CLIENT_TYPE: str = "&clienttype="
    CLOSEST: str = "&closest="
    CONTRACT_ADDRESS: str = "&contractaddress="
    DATA: str = "&data="
    END_BLOCK: str = "&endblock="
    END_DATE: str = "&enddate="
    GAS_PRICE: str = "&gasPrice="
    GAS: str = "&gas="
    HEX: str = "&hex="
    INDEX: str = "&index="
    MODULE: str = "module="
    OFFSET: str = "&offset="
    PAGE: str = "&page="
    POSITION: str = "&position="
    PREFIX: str = "https://api-{}.etherscan.io/api?"
    SORT: str = "&sort="
    START_BLOCK: str = "&startblock="
    START_DATE: str = "&startdate="
    SYNC_MODE: str = "&syncmode="
    TAG: str = "&tag="
    TIMESTAMP: str = "&timestamp="
    TO: str = "&to="
    TXHASH: str = "&txhash="
    VALUE: str = "&value="

@dataclass(frozen=True)
class TagsEnum:
    ACCOUNT: str = "account"
    LATEST: str = "latest"